### ISSUE TITLE
[Feature] Add social links

### ISSUE THREAD

**Issue by jonathondgebhardt** [JustBarnt/HairByMorgan#1]
Some text in the page says to keep an eye out for social links but there are none. These used to be on the original version of the site.

- Instagram: https://www.instagram.com/morgangebhardthair/
- Facebook: https://www.facebook.com/profile.php?id=100063681005365

We may also want a link to her new salon's booking, but I'll keep you posted.

**Comment by JustBarnt** [comment]
Oops, yup. Meant to ask which ones to included marking this as a big instead. Thanks!
